routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

function reportInvoice()
{
    Route::get('report/invoice/entry/{id}', 'ReportController@invoiceHairdress')->name('report.invoice');
}

Route::get('/', fn () => redirect(route('login')));
Auth::routes(['register' => false]);

Route::prefix('search')
    ->name('search.')
    ->group(function () {
        Route::get('worker/', 'SearchController@worker')->name('worker');
        Route::get('subscriber/', 'SearchController@subscriber')->name('subscriber');
    });

Route::middleware(['auth:web'])
    ->group(function () {
        reportInvoice();
        Route::get('home/', 'HomeController@index')->name('home');
        Route::put('password/change', 'HomeController@changePassword')->name('change-password');

        Route::prefix('hairdress')
            ->name('hairdress')
            ->middleware('can:not-cashier')
            ->group(function () {
                Route::get('', 'HairdressController@home');
                Route::get('bonus/', 'HairdressController@bonus')->name('.bonus');
                Route::get('dept/', 'HairdressController@dept')->name('.dept');
                Route::get('salary/', 'HairdressController@salary')->name('.salary');
                Route::get('hairdressing/', 'HairdressController@hairdressing')->name('.hairdressing');
            });

        Route::namespace('Checkout')
            ->middleware('can:view-cashier')
            ->group(function () {
                Route::prefix('collect')
                    ->name('collect')
                    ->group(function () {
                        Route::get('', 'CollectController@home');
                        Route::get('entries/', 'CollectController@entries')->name('.entries');
                        Route::get('entries/search', 'CollectController@entriesSearch')->name('.entries.search');

                        Route::get('entries/profile/worker', 'CollectController@profileWorker')
                            ->name('.profile.worker')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);
                        Route::get('entries/profile/subscriber', 'CollectController@profileSubcriber')
                            ->name('.profile.subscriber')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);

                        Route::post('entries/new', 'CollectController@newEntry')->name('.profile.newEntry');

                        Route::get('bonus/', 'CollectController@bonus')->name('.bonus');
                        Route::get('bonus/add-bonus', 'CollectController@addBonus')->name('.bonus.add-bonus');
                        Route::post('bonus/add-bonus', 'CollectController@newBonus')->name('.bonus.newBonus');
                    });
                Route::prefix('disburse')
                    ->name('disburse')
                    ->group(function () {
                        Route::get('', 'DisburseController@home');
                        Route::get('sortie/', 'DisburseController@sortie')->name('.sortie');
                        Route::post('sortie/new', 'DisburseController@newSortie')->name('.newSortie');

                        Route::get('rejected/', 'DisburseController@rejected')->name('.rejected');
                        Route::get('unconfirmed/', 'DisburseController@unconfirmed')->name('.unconfirmed');
                        Route::get('search/', 'DisburseController@search')->name('.search');
                    });
            });

        Route::get('report/', 'HomeController@report')->name('report');
    });

Route::prefix('admin')->name('admin.')
    ->group(function () {
        Route::namespace('Admin\Auth')
            ->group(function () {
                Route::get('login/', "AdminLoginController@showLoginForm")->name('login');
                Route::post('login/', "AdminLoginController@login")->name('log-in');
            });
        Route::middleware(['auth.admin:admin'])
            ->group(function () {
                reportInvoice();
                Route::namespace('Admin')
                    ->group(function () {
                        Route::namespace('Auth')
                            ->group(function () {
                                Route::post('logout/', "AdminLoginController@logout")->name('logout');
                            });
                        Route::get('', "HomeController@index")->name('home');

                        Route::prefix('workers')
                            ->group(function () {
                                Route::get('', "AdminController@workers")->name('workers');
                                Route::post('', "AdminController@createWorker")->name('createWorker');
                                Route::get('cashier/', "AdminController@cashier")->name('cashier');
                                Route::put('modif/{id}/', "AdminController@modifyWorker")->name('modifyWorker');
                                Route::delete('del/{id}/', "AdminController@deleteWorkers")->name('deleteWorker');
                            });

                        Route::prefix('specifications')
                            ->group(function () {
                                Route::get('', "AdminController@specifications")->name('specifications');
                                Route::post('', "AdminController@newSpecification")->name('newSpecification');
                                Route::put('modif/{id}', "AdminController@modifySpecification")->name('modifySpecification');
                                Route::delete('del/{id}/', "AdminController@deleteSpecification")->name('deleteSpecification');

                                Route::get('paytype/', "AdminController@payType")->name('payType');
                                Route::post('newPayType/', "AdminController@newPayType")->name('newPayType');
                                Route::delete('payType/delete/{id}', "AdminController@deletePayType")->name('deletePayType');
                            });

                        Route::prefix('subsribers')
                            ->group(function () {
                                Route::get('', "SubscriberController@subscribers")->name('subscribers');
                                Route::post('', "SubscriberController@newSubscriber")->name('newSubscriber');

                                Route::put('modif/{id}/', "SubscriberController@modifysubsriber")->name('modifySubsriber');
                                Route::delete('del/{id}/', "SubscriberController@deletesubsribers")->name('deleteSubsriber');
                                Route::get('profile/', "SubscriberController@subsriberProfile")->name('subscriber.profile');

                                Route::get('subscriptions/{id?}', "SubscriberController@subscriptions")->name('subscriptions');
                                Route::post('subscription/', "SubscriberController@newSubscription")->name('newSubscription');
                                Route::put('subscription/modif/{id}', "SubscriberController@modifySubscription")->name('modifySubscription');
                                Route::delete('subscription/delete/{id}', "SubscriberController@deleteSubscription")->name('deleteSubscription');
                            });

                        Route::prefix('products')
                            ->group(function () {
                                Route::get('', "ProductsController@products")->name('products');
                                Route::post('', "ProductsController@newMaterial")->name('newMaterial');
                                Route::delete('del/{id}', "ProductsController@deleteProduct")->name('deleteProduct');
                                Route::put('modif/{id}', "ProductsController@modifyProduct")->name('modifyProduct');
                                Route::get('inventory/', "ProductsController@inventory")->name('products.inventory');
                            });

                        Route::prefix('disbursement')
                            ->name('disbursement')
                            ->group(function () {
                                Route::get('', "DisbursementController@disbursement");
                                Route::put('disbursement/approved/{id}', "DisbursementController@disburseApproved")->name('.approved');
                                Route::get('confirmed/', "DisbursementController@confirmed")->name('.confirmed');
                                Route::get('rejected/', "DisbursementController@rejected")->name('.rejected');
                                Route::get('request/', "DisbursementController@request")->name('.request');
                                Route::get('inventory/', "DisbursementController@inventory")->name('.inventory');
                            });

                        Route::prefix('collection')
                            ->name('collection.')
                            ->group(function () {
                                Route::get('', "CollectionController@hairdressing")->name('hairdressing');
                                Route::put('hairdressing/approved/{id}', "CollectionController@hairdressingApproved")->name('hairdressing.approved');

                                Route::get('bonus/', "CollectionController@bonus")->name('bonus');
                                Route::put('bonus/approved/{id}', "CollectionController@bonusApproved")->name('bonus.approved');
                            });
                        Route::prefix('user')

resources/views/admin/collection.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Entrés') }}</h1>
</div>
<div data-controller="Admin-Collect">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.collection.hairdressing') ? 'active' : '' }}" 
                    href="{{ route('admin.collection.hairdressing') }}">{{ __('coiffure') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.collection.bonus') ? 'active' : '' }}"
                        href="{{ route('admin.collection.bonus') }}">{{ __('Bonus') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('collection')
        </div>
    </div>
</div>

@endsection

resources/views/admin/disbursement.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Sorties') }}</h1>
</div>
<div data-controller="Disbursement">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.disbursement') ? 'active' : '' }}" 
                    href="{{ route('admin.disbursement') }}">{{ __('Décaissement') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.disbursement.confirmed') ? 'active' : '' }}"
                        href="{{ route('admin.disbursement.confirmed') }}">{{ __('Confirmés') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.disbursement.rejected') ? 'active' : '' }}"
                        href="{{ route('admin.disbursement.rejected') }}">{{ __('Rejetés') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.disbursement.request') ? 'active' : '' }}"
                        href="{{ route('admin.disbursement.request') }}">{{ __('Confirmation') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.disbursement.inventory') ? 'active' : '' }}"
                        href="{{ route('admin.disbursement.inventory') }}">{{ __('Inventaire') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('disbursement')
        </div>
    </div>
</div>

@endsection

resources/views/admin/home.blade.php
@extends('layouts.app-admin')

@section('admin')
<div data-controller="Admin-Home">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tableau de bord</h1>
        <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm report-modal" data-url="{{ route('admin.report.generate') }}"><i
                class="fas fa-download fa-sm text-white-50"></i>Générer un rapport</button>
    </div>
    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Coiffeurs</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $user }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Abonnés</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $subcriber }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">Materiels</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $material }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Bonus</div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ $bonus }}%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar" style="width: {{ $bonus }}%"
                                            aria-valuenow="{{ $bonus }}" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Encaissement</h6>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="collect-chart"></canvas>
                    </div>
                </div>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Sorties</h6>
                </div>
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="disburse-chart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Activités utilisateurs</h6>
                </div>
                <div class="card-body">
                    <ul class="list-group mb-3">
                        @foreach ($activities as $activity)
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ $activity->logable->email }}</h6>
                                <small class="text-muted">
                                    {{ $activity->logable->created_at }}
                                </small>
                            </div>
                        </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.chart_collect = @json($chart_collect);
    window.chart_disburse = @json($chart_disburse);
</script>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.app')

@section('style')
<style>
    .form-signin {
        width: 100%;
        max-width: 420px;
        padding: 15px;
        margin: auto;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group>input,
    .form-label-group>label {
        height: 3.125rem;
        padding: .75rem;
    }

    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        line-height: 1.5;
        color: #495057;
        pointer-events: none;
        cursor: text;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-moz-placeholder {
        color: transparent;
    }

    .form-label-group input::placeholder {
        color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
        padding-top: 1.25rem;
        padding-bottom: .25rem;
    }

    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: .25rem;
        padding-bottom: .25rem;
        font-size: 12px;
        color: #777;
    }

    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }

    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }

</style>
@endsection
@section('content')
<form class="form-signin" method="POST" action="{{ route('admin.log-in') }}">
    @csrf
    <div class="text-center mb-4 mt-5">
        <h1 class="h3 mb-3 font-weight-normal">{{ config('app.name', 'Laravel') }}</h1>
        <p>Administration</p>
    </div>

    <div class="form-label-group">
        <input type="email" id="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" placeholder="Email adresse" required autofocus>
        <label for="email">{{ __('E-Mail Adresse') }}</label>
        @error('email')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>

    <div class="form-label-group">
        <input type="password" id="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password" required>
        <label for="password">{{ __('Mot de passe') }}</label>
        @error('password')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}>
            {{ __('Se souvenir') }}
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Connexion</button>
</form>
@endsection

resources/views/admin/products.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Materiels') }}</h1>
</div>
<div data-controller="Products">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.products.inventory') ? 'active' : '' }}" 
                    href="{{ route('admin.products.inventory') }}">{{ __('Inventaire') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.products') ? 'active' : '' }}"
                        href="{{ route('admin.products') }}">{{ __('Materiels') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('products')
        </div>
    </div>
</div>

@endsection

resources/views/admin/report.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Rapports') }}</h1>
</div>
<div data-controller="Admin-Report" class="my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-12">
            <div class="card">
                <div class="card-header"><small>Repport</small></div>
                <div class="card-body">
                    <form action="{{ route('admin.report.generate') }}" data-action="Admin-Report#report" method="GET" class="form">
                        <ul>
                            <ol>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="report-by-select" name="report-select"
                                        class="custom-control-input">
                                    <label class="custom-control-label" for="report-by-select">Rapport par
                                        Selection</label>
                                </div>
                                <ul>
                                    <ol>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" disabled name="list-workers" class="custom-control-input" id="list-workers">
                                            <label class="custom-control-label" for="list-workers">Liste
                                                Travaillleurs</label>
                                        </div>
                                    </ol>
                                    <ol>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" disabled name="list-subscriber" class="custom-control-input" id="list-subscriber">
                                            <label class="custom-control-label" for="list-subscriber">Liste
                                                Abonné</label>
                                        </div>
                                    </ol>
                                    <ol>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" disabled name="list-material" class="custom-control-input" id="list-material">
                                            <label class="custom-control-label" for="list-material">Liste
                                                Materiel</label>
                                        </div>
                                    </ol>
                                    <ol>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" disabled name="list-specification" class="custom-control-input" id="list-specification">
                                            <label class="custom-control-label" for="list-specification">Liste
                                                Spécification</label>
                                        </div>
                                    </ol>
                                </ul>
                            </ol>
                            <ol>
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="general-report" checked name="report-select"
                                        class="custom-control-input">
                                    <label class="custom-control-label" for="general-report">Rapport general</label>
                                </div>
                            </ol>
                        </ul>
                        <button type="submit" class="btn btn-sm btn-primary">Generer Rapport</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/specifications.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Specifications') }}</h1>
</div>
<div data-controller="Specifications">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.specifications') ? 'active' : '' }}" href="{{ route('admin.specifications') }}">{{ __('Specifications') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.payType') ? 'active' : '' }}" href="{{ route('admin.payType') }}">{{ __('Mode Paie') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('specifications')
        </div>
    </div>
</div>

@endsection

resources/views/admin/subscribers.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Abonnés') }}</h1>
</div>
<div data-controller="Subscribers">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.subscribers') ? 'active' : '' }}" href="{{ route('admin.subscribers') }}">{{ __('Abonnés') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.subscriptions') ? 'active' : '' }}" href="{{ route('admin.subscriptions') }}">{{ __('Abonnements') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.subscriber.profile') ? 'active' : '' }}" href="{{ route('admin.subscriber.profile') }}">{{ __('Profile') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('subscribers')
        </div>
    </div>
</div>

@endsection

resources/views/admin/user-admin.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
<h1 class="h3 mb-0 text-gray-800">{{Auth::user('admin')->email }}</h1>
</div>
<div data-controller="UserAdmin">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.user.profile') ? 'active' : '' }}" href="{{ route('admin.user.profile') }}">{{ __('Profile') }}</a>
                </li>
                @if (Auth::user('admin')->can('view-super'))
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.user.settings') ? 'active' : '' }}" href="{{ route('admin.user.settings') }}">{{ __('Parametre') }}</a>
                </li>
                @endif
            </ul>
        </div>
        <div class="card-body">
            @yield('user-admin')
        </div>
    </div>
</div>
@endsection

resources/views/admin/workers.blade.php
@extends('layouts.app-admin')

@section('admin')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ __('Travailleurs') }}</h1>
</div>
<div data-controller="Worker">
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.workers') ? 'active' : '' }}" href="{{ route('admin.workers') }}">{{ __('Travailleurs') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Request::url() == route('admin.cashier') ? 'active' : '' }}" href="{{ route('admin.cashier') }}">{{ __('Caissiers et Moderateurs') }}</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            @yield('workers')
        </div>
    </div>
</div>

@endsection