routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

function reportInvoice()
{
    Route::get('report/invoice/entry/{id}', 'ReportController@invoiceHairdress')->name('report.invoice');
}

Route::get('/', fn () => redirect(route('login')));
Auth::routes(['register' => false]);

Route::prefix('search')
    ->name('search.')
    ->group(function () {
        Route::get('worker/', 'SearchController@worker')->name('worker');
        Route::get('subscriber/', 'SearchController@subscriber')->name('subscriber');
    });

Route::middleware(['auth:web'])
    ->group(function () {
        reportInvoice();
        Route::get('home/', 'HomeController@index')->name('home');
        Route::put('password/change', 'HomeController@changePassword')->name('change-password');

        Route::prefix('hairdress')
            ->name('hairdress')
            ->middleware('can:not-cashier')
            ->group(function () {
                Route::get('', 'HairdressController@home');
                Route::get('bonus/', 'HairdressController@bonus')->name('.bonus');
                Route::get('dept/', 'HairdressController@dept')->name('.dept');
                Route::get('salary/', 'HairdressController@salary')->name('.salary');
                Route::get('hairdressing/', 'HairdressController@hairdressing')->name('.hairdressing');
            });

        Route::namespace('Checkout')
            ->middleware('can:view-cashier')
            ->group(function () {
                Route::prefix('collect')
                    ->name('collect')
                    ->group(function () {
                        Route::get('', 'CollectController@home');
                        Route::get('entries/', 'CollectController@entries')->name('.entries');
                        Route::get('entries/search', 'CollectController@entriesSearch')->name('.entries.search');

                        Route::get('entries/profile/worker', 'CollectController@profileWorker')
                            ->name('.profile.worker')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);
                        Route::get('entries/profile/subscriber', 'CollectController@profileSubcriber')
                            ->name('.profile.subscriber')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);

                        Route::post('entries/new', 'CollectController@newEntry')->name('.profile.newEntry');

                        Route::get('bonus/', 'CollectController@bonus')->name('.bonus');
                        Route::get('bonus/add-bonus', 'CollectController@addBonus')->name('.bonus.add-bonus');
                        Route::post('bonus/add-bonus', 'CollectController@newBonus')->name('.bonus.newBonus');
                    });
                Route::prefix('disburse')
                    ->name('disburse')
                    ->group(function () {
                        Route::get('', 'DisburseController@home');
                        Route::get('sortie/', 'DisburseController@sortie')->name('.sortie');
                        Route::post('sortie/new', 'DisburseController@newSortie')->name('.newSortie');

                        Route::get('rejected/', 'DisburseController@rejected')->name('.rejected');
                        Route::get('unconfirmed/', 'DisburseController@unconfirmed')->name('.unconfirmed');
                        Route::get('search/', 'DisburseController@search')->name('.search');
                    });
            });

        Route::get('report/', 'HomeController@report')->name('report');
    });

Route::prefix('admin')->name('admin.')
    ->group(function () {
        Route::namespace('Admin\Auth')
            ->group(function () {
                Route::get('login/', "AdminLoginController@showLoginForm")->name('login');
                Route::post('login/', "AdminLoginController@login")->name('log-in');
            });
        Route::middleware(['auth.admin:admin'])
            ->group(function () {
                reportInvoice();
                Route::namespace('Admin')
                    ->group(function () {
                        Route::namespace('Auth')
                            ->group(function () {
                                Route::post('logout/', "AdminLoginController@logout")->name('logout');
                            });
                        Route::get('', "HomeController@index")->name('home');

                        Route::prefix('workers')
                            ->group(function () {
                                Route::get('', "AdminController@workers")->name('workers');
                                Route::post('', "AdminController@createWorker")->name('createWorker');
                                Route::get('cashier/', "AdminController@cashier")->name('cashier');
                                Route::put('modif/{id}/', "AdminController@modifyWorker")->name('modifyWorker');
                                Route::delete('del/{id}/', "AdminController@deleteWorkers")->name('deleteWorker');
                            });

                        Route::prefix('specifications')
                            ->group(function () {
                                Route::get('', "AdminController@specifications")->name('specifications');
                                Route::post('', "AdminController@newSpecification")->name('newSpecification');
                                Route::put('modif/{id}', "AdminController@modifySpecification")->name('modifySpecification');
                                Route::delete('del/{id}/', "AdminController@deleteSpecification")->name('deleteSpecification');

                                Route::get('paytype/', "AdminController@payType")->name('payType');
                                Route::post('newPayType/', "AdminController@newPayType")->name('newPayType');
                                Route::delete('payType/delete/{id}', "AdminController@deletePayType")->name('deletePayType');
                            });

                        Route::prefix('subsribers')
                            ->group(function () {
                                Route::get('', "SubscriberController@subscribers")->name('subscribers');
                                Route::post('', "SubscriberController@newSubscriber")->name('newSubscriber');

                                Route::put('modif/{id}/', "SubscriberController@modifysubsriber")->name('modifySubsriber');
                                Route::delete('del/{id}/', "SubscriberController@deletesubsribers")->name('deleteSubsriber');
                                Route::get('profile/', "SubscriberController@subsriberProfile")->name('subscriber.profile');

                                Route::get('subscriptions/{id?}', "SubscriberController@subscriptions")->name('subscriptions');
                                Route::post('subscription/', "SubscriberController@newSubscription")->name('newSubscription');
                                Route::put('subscription/modif/{id}', "SubscriberController@modifySubscription")->name('modifySubscription');
                                Route::delete('subscription/delete/{id}', "SubscriberController@deleteSubscription")->name('deleteSubscription');
                            });

                        Route::prefix('products')
                            ->group(function () {
                                Route::get('', "ProductsController@products")->name('products');
                                Route::post('', "ProductsController@newMaterial")->name('newMaterial');
                                Route::delete('del/{id}', "ProductsController@deleteProduct")->name('deleteProduct');
                                Route::put('modif/{id}', "ProductsController@modifyProduct")->name('modifyProduct');
                                Route::get('inventory/', "ProductsController@inventory")->name('products.inventory');
                            });

                        Route::prefix('disbursement')
                            ->name('disbursement')
                            ->group(function () {
                                Route::get('', "DisbursementController@disbursement");
                                Route::put('disbursement/approved/{id}', "DisbursementController@disburseApproved")->name('.approved');
                                Route::get('confirmed/', "DisbursementController@confirmed")->name('.confirmed');
                                Route::get('rejected/', "DisbursementController@rejected")->name('.rejected');
                                Route::get('request/', "DisbursementController@request")->name('.request');
                                Route::get('inventory/', "DisbursementController@inventory")->name('.inventory');
                            });

                        Route::prefix('collection')
                            ->name('collection.')
                            ->group(function () {
                                Route::get('', "CollectionController@hairdressing")->name('hairdressing');
                                Route::put('hairdressing/approved/{id}', "CollectionController@hairdressingApproved")->name('hairdressing.approved');

                                Route::get('bonus/', "CollectionController@bonus")->name('bonus');
                                Route::put('bonus/approved/{id}', "CollectionController@bonusApproved")->name('bonus.approved');
                            });
                        Route::prefix('user')

resources/views/admin/_workers/cashier.blade.php
@extends('admin.workers')

@section('workers')
<div class="justify-content-center">
    <div class="mb-4">
        {{-- <form class="d-sm-inline-block form-inline  mw-100 navbar-search">
            <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" value="{{ request('search') }}" name="search" placeholder="Recherche" />
            </div>
        </form> --}}
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ __('Nom') }}</th>
                            <th scope="col">{{ __('Email') }}</th>
                            <th scope="col">{{ __('Tel') }}</th>
                            <th scope="col">{{ __('Adresse') }}</th>
                            <th scope="col">{{ __('Status') }}</th>
                            <th scope="col">{{ __('Profile') }}</th>
                            <th scope="col">{{ __('Modifier') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->phone }}</td>
                            <td>{{ $user->address }}</td>
                            <td class="{{ ($user->moderator || $user->cashier) ? 'text-success': '' }}">
                                {{ $user->moderator ? 'Moderateur, ': '' }}
                                {{ $user->cashier ? 'Caissier': '' }}
                                {{ !$user->moderator && !$user->cashier ? 'Aucun': '' }}
                            </td>
                            <td class="{{ $user->active ? 'text-success': 'text-danger' }}">
                                @if($user->active)
                                <span class="badge badge-success">Actif</span>
                                @else
                                <span class="badge badge-danger">Inactif</span>
                                @endif
                            </td>
                            @include('template.admin.option-table', ['user' => $user, 'routeModif' => 'admin.modifyWorker', 'routeDelete' => 'admin.deleteWorker'])
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{ $users->links() }}
</div>
<x-user-modify>
<div class="form-row">
    <div class="col-md-4 mb-3">
        <label for="d-name">{{ __('Nom') }}</label>
        <input type="text" class="form-control" name="name" id="d-name" required>
    </div>
    <div class="col-md-4 mb-3">
        <label for="d-email">{{ __('E-mail Adresse') }}</label>
        <input type="email" class="form-control" name="email" id="d-email" required>
    </div>
    <div class="col-md-4 mb-3">
        <label for="d-address">{{ __('Adresse') }}</label>
        <input type="text" name="address" class="form-control" id="d-address" required>
    </div>
</div>
<div class="form-row">
    <div class="col-md-6 mb-3">
        <label for="d-phone">{{ __('Tel') }}</label>
        <input type="tel" name="phone" class="form-control" id="d-phone" required>
    </div>
    <div class="col-md-3 mb-3">
        <label for="d-password">{{ __('Mot de passe') }}</label>
        <input type="password" name="password" class="form-control" id="d-password">
    </div>

    <div class="col-md-3 mb-3">
        <label for="d-password_confirmation">{{ __('Confirmer mot de passe') }}</label>
        <input type="password" name="password_confirmation" class="form-control" id="d-password_confirmation">
    </div>
</div>
<div class="form-group">
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="moderator" id="d-moderator">
        <label class="form-check-label" for="d-moderator">
            {{ __('Moderateur') }}
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="cashier" id="d-cashier">
        <label class="form-check-label" for="d-cashier">
            {{ __('Caissier') }}
        </label>
    </div>
</div>
</x-user-modify>

@endsection

resources/views/admin/_workers/workers.blade.php
@extends('admin.workers')

@section('workers')
<div class="justify-content-center">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-3">
                    <form action="" class=" d-inline-block form-inline w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-0 small" value="{{ request('search') }}"
                                name="search" placeholder="Recherche" />
                        </div>
                    </form>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-primary btn-sm btn-icon-split" data-toggle="modal" data-target="#newWorker">
                        <span class="text">{{ __('Nouveau travailleur') }}</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ __('Nom') }}</th>
                            <th scope="col">{{ __('Email') }}</th>
                            <th scope="col">{{ __('Tel') }}</th>
                            <th scope="col">{{ __('Adresse') }}</th>
                            <th scope="col">{{ __('Status') }}</th>
                            <th scope="col">{{ __('Profile') }}</th>
                            <th scope="col">{{ __('Modifier') }}</th>
                            <th scope="col">{{ __('Contact') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->phone }}</td>
                            <td>{{ $user->address }}</td>
                            <td class="{{ $user->moderator ? 'text-success': '' }}">
                                {{ $user->moderator ? 'Moderateur, ': '' }}
                                {{ $user->cashier ? 'Caissier': '' }}
                                {{ !$user->moderator && !$user->cashier ? 'Aucun': '' }}
                            </td>
                            <td class="{{ $user->active ? 'text-success': 'text-danger' }}">
                                @if($user->active)
                                <span class="badge badge-success">Actif</span>
                                @else
                                <span class="badge badge-danger">Inactif</span>
                                @endif
                            </td>
                            @include('template.admin.option-table',
                            ['user' => $user, 'routeModif' => 'admin.modifyWorker', 'routeDelete' => 'admin.deleteWorker'])
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{ $users->links() }}
</div>
<div class="modal fade" id="newWorker" tabindex="-1" role="dialog" aria-labelledby="newWorkerTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newWorkerTitle">{{ __('Ajouter Travailleur') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="needs-validation" method="POST" action="{{ route('admin.createWorker') }}"
                data-action="Worker#createWorker">
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label for="name">{{ __('Nom') }}</label>
                            <input type="text" class="form-control" name="name" id="name" required>
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="email">{{ __('E-mail Adresse') }}</label>
                            <input type="email" class="form-control" name="email" id="email" required>
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="address">{{ __('Adresse') }}</label>
                            <input type="text" name="address" class="form-control" id="address" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="phone">{{ __('Tel') }}</label>
                            <input type="tel" name="phone" class="form-control" id="phone" required>
                        </div>
                        <div class="col-md-3 mb-3">
                            <label for="password">{{ __('Mot de passe') }}</label>
                            <input type="password" name="password" class="form-control" id="password" required>
                        </div>

                        <div class="col-md-3 mb-3">
                            <label for="password_confirmation">{{ __('Confirmer mot de passe') }}</label>
                            <input type="password" name="password_confirmation" class="form-control"
                                id="password_confirmation" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="moderator" id="moderator">
                            <label class="form-check-label" for="moderator">
                                {{ __('Moderateur') }}
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="cashier" id="cashier">
                            <label class="form-check-label" for="cashier">
                                {{ __('Caissier') }}
                            </label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Fermer') }}</button>
                    <button type="submit" class="btn btn-primary">{{ __('Enregistrer') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

<x-user-modify>
<div class="form-row">
    <div class="col-md-4 mb-3">
        <label for="d-name">{{ __('Nom') }}</label>
        <input type="text" class="form-control" name="name" id="d-name" required>
    </div>
    <div class="col-md-4 mb-3">
        <label for="d-email">{{ __('E-mail Adresse') }}</label>
        <input type="email" class="form-control" name="email" id="d-email" required>
    </div>
    <div class="col-md-4 mb-3">
        <label for="d-address">{{ __('Adresse') }}</label>
        <input type="text" name="address" class="form-control" id="d-address" required>
    </div>
</div>
<div class="form-row">
    <div class="col-md-6 mb-3">
        <label for="d-phone">{{ __('Tel') }}</label>
        <input type="tel" name="phone" class="form-control" id="d-phone" required>
    </div>
    <div class="col-md-3 mb-3">
        <label for="d-password">{{ __('Mot de passe') }}</label>
        <input type="password" name="password" class="form-control" id="d-password">
    </div>

    <div class="col-md-3 mb-3">
        <label for="d-password_confirmation">{{ __('Confirmer mot de passe') }}</label>
        <input type="password" name="password_confirmation" class="form-control" id="d-password_confirmation">
    </div>
</div>
<div class="form-group">
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="moderator" id="d-moderator">
        <label class="form-check-label" for="d-moderator">
            {{ __('Moderateur') }}
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="cashier" id="d-cashier">
        <label class="form-check-label" for="d-cashier">
            {{ __('Caissier') }}
        </label>
    </div>
</div>
</x-user-modify>


@endsection