routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

function reportInvoice()
{
    Route::get('report/invoice/entry/{id}', 'ReportController@invoiceHairdress')->name('report.invoice');
}

Route::get('/', fn () => redirect(route('login')));
Auth::routes(['register' => false]);

Route::prefix('search')
    ->name('search.')
    ->group(function () {
        Route::get('worker/', 'SearchController@worker')->name('worker');
        Route::get('subscriber/', 'SearchController@subscriber')->name('subscriber');
    });

Route::middleware(['auth:web'])
    ->group(function () {
        reportInvoice();
        Route::get('home/', 'HomeController@index')->name('home');
        Route::put('password/change', 'HomeController@changePassword')->name('change-password');

        Route::prefix('hairdress')
            ->name('hairdress')
            ->middleware('can:not-cashier')
            ->group(function () {
                Route::get('', 'HairdressController@home');
                Route::get('bonus/', 'HairdressController@bonus')->name('.bonus');
                Route::get('dept/', 'HairdressController@dept')->name('.dept');
                Route::get('salary/', 'HairdressController@salary')->name('.salary');
                Route::get('hairdressing/', 'HairdressController@hairdressing')->name('.hairdressing');
            });

        Route::namespace('Checkout')
            ->middleware('can:view-cashier')
            ->group(function () {
                Route::prefix('collect')
                    ->name('collect')
                    ->group(function () {
                        Route::get('', 'CollectController@home');
                        Route::get('entries/', 'CollectController@entries')->name('.entries');
                        Route::get('entries/search', 'CollectController@entriesSearch')->name('.entries.search');

                        Route::get('entries/profile/worker', 'CollectController@profileWorker')
                            ->name('.profile.worker')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);
                        Route::get('entries/profile/subscriber', 'CollectController@profileSubcriber')
                            ->name('.profile.subscriber')
                            ->withoutMiddleware(['auth:web', 'can:view-cashier']);

                        Route::post('entries/new', 'CollectController@newEntry')->name('.profile.newEntry');

                        Route::get('bonus/', 'CollectController@bonus')->name('.bonus');
                        Route::get('bonus/add-bonus', 'CollectController@addBonus')->name('.bonus.add-bonus');
                        Route::post('bonus/add-bonus', 'CollectController@newBonus')->name('.bonus.newBonus');
                    });
                Route::prefix('disburse')
                    ->name('disburse')
                    ->group(function () {
                        Route::get('', 'DisburseController@home');
                        Route::get('sortie/', 'DisburseController@sortie')->name('.sortie');
                        Route::post('sortie/new', 'DisburseController@newSortie')->name('.newSortie');

                        Route::get('rejected/', 'DisburseController@rejected')->name('.rejected');
                        Route::get('unconfirmed/', 'DisburseController@unconfirmed')->name('.unconfirmed');
                        Route::get('search/', 'DisburseController@search')->name('.search');
                    });
            });

        Route::get('report/', 'HomeController@report')->name('report');
    });

Route::prefix('admin')->name('admin.')
    ->group(function () {
        Route::namespace('Admin\Auth')
            ->group(function () {
                Route::get('login/', "AdminLoginController@showLoginForm")->name('login');
                Route::post('login/', "AdminLoginController@login")->name('log-in');
            });
        Route::middleware(['auth.admin:admin'])
            ->group(function () {
                reportInvoice();
                Route::namespace('Admin')
                    ->group(function () {
                        Route::namespace('Auth')
                            ->group(function () {
                                Route::post('logout/', "AdminLoginController@logout")->name('logout');
                            });
                        Route::get('', "HomeController@index")->name('home');

                        Route::prefix('workers')
                            ->group(function () {
                                Route::get('', "AdminController@workers")->name('workers');
                                Route::post('', "AdminController@createWorker")->name('createWorker');
                                Route::get('cashier/', "AdminController@cashier")->name('cashier');
                                Route::put('modif/{id}/', "AdminController@modifyWorker")->name('modifyWorker');
                                Route::delete('del/{id}/', "AdminController@deleteWorkers")->name('deleteWorker');
                            });

                        Route::prefix('specifications')
                            ->group(function () {
                                Route::get('', "AdminController@specifications")->name('specifications');
                                Route::post('', "AdminController@newSpecification")->name('newSpecification');
                                Route::put('modif/{id}', "AdminController@modifySpecification")->name('modifySpecification');
                                Route::delete('del/{id}/', "AdminController@deleteSpecification")->name('deleteSpecification');

                                Route::get('paytype/', "AdminController@payType")->name('payType');
                                Route::post('newPayType/', "AdminController@newPayType")->name('newPayType');
                                Route::delete('payType/delete/{id}', "AdminController@deletePayType")->name('deletePayType');
                            });

                        Route::prefix('subsribers')
                            ->group(function () {
                                Route::get('', "SubscriberController@subscribers")->name('subscribers');
                                Route::post('', "SubscriberController@newSubscriber")->name('newSubscriber');

                                Route::put('modif/{id}/', "SubscriberController@modifysubsriber")->name('modifySubsriber');
                                Route::delete('del/{id}/', "SubscriberController@deletesubsribers")->name('deleteSubsriber');
                                Route::get('profile/', "SubscriberController@subsriberProfile")->name('subscriber.profile');

                                Route::get('subscriptions/{id?}', "SubscriberController@subscriptions")->name('subscriptions');
                                Route::post('subscription/', "SubscriberController@newSubscription")->name('newSubscription');
                                Route::put('subscription/modif/{id}', "SubscriberController@modifySubscription")->name('modifySubscription');
                                Route::delete('subscription/delete/{id}', "SubscriberController@deleteSubscription")->name('deleteSubscription');
                            });

                        Route::prefix('products')
                            ->group(function () {
                                Route::get('', "ProductsController@products")->name('products');
                                Route::post('', "ProductsController@newMaterial")->name('newMaterial');
                                Route::delete('del/{id}', "ProductsController@deleteProduct")->name('deleteProduct');
                                Route::put('modif/{id}', "ProductsController@modifyProduct")->name('modifyProduct');
                                Route::get('inventory/', "ProductsController@inventory")->name('products.inventory');
                            });

                        Route::prefix('disbursement')
                            ->name('disbursement')
                            ->group(function () {
                                Route::get('', "DisbursementController@disbursement");
                                Route::put('disbursement/approved/{id}', "DisbursementController@disburseApproved")->name('.approved');
                                Route::get('confirmed/', "DisbursementController@confirmed")->name('.confirmed');
                                Route::get('rejected/', "DisbursementController@rejected")->name('.rejected');
                                Route::get('request/', "DisbursementController@request")->name('.request');
                                Route::get('inventory/', "DisbursementController@inventory")->name('.inventory');
                            });

                        Route::prefix('collection')
                            ->name('collection.')
                            ->group(function () {
                                Route::get('', "CollectionController@hairdressing")->name('hairdressing');
                                Route::put('hairdressing/approved/{id}', "CollectionController@hairdressingApproved")->name('hairdressing.approved');

                                Route::get('bonus/', "CollectionController@bonus")->name('bonus');
                                Route::put('bonus/approved/{id}', "CollectionController@bonusApproved")->name('bonus.approved');
                            });
                        Route::prefix('user')

app/Models/Salary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Salary extends Model
{
    /**
     * Undocumented variable
     *
     * @var string
     */
    protected $table = 'salaries';

    /**
     * Undocumented variable
     *
     * @var array
     */
    protected $fillable = ['amount', 'expected', 'approved', 'rejected'];

     /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

resources/views/admin/_salary/_salaries/hairdresser.blade.php
@extends('admin._salary.salaries')

@section('salaries')
<div class="justify-content-center">
    <div class="card">
        <div class="card-header d-flex justify-content-between">
            <form method="GET" class="d-inline-block" action="" autocomplete="off">
                <input type="hidden" name="uid" value="{{ request('uid') }}">
                <div class="form-row">
                    <div class="col-lg-3 col-sm-12 col-sm-12 mb-3">
                        <div>
                            <button type="button" class="btn  btn-block btn-outline-info dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Recherche Travailleur
                            </button>
                            <div class="dropdown-menu shadow">
                                <div class="mx-1">
                                    <div class="input-group">
                                        <input type="text" data-url="{{ route('search.worker') }}"
                                            data-target="Admin-Salary.hlsS"
                                            class="form-control bg-light border-0 small" placeholder="Recherche...">
                                    </div>
                                </div>
                                <div class="dropdown-divider mx-2" style="padding: 0 150px"></div>
                                <div data-target="Admin-Salary.hlsSList"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                        <input type="text" class="form-control" id="worker_nameS" value="{{ $us ? $us->name : '' }}" readonly
                            placeholder="Travailleur (optionnel)">
                        <div class="valid-feedback"></div>
                    </div>
                    <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                        <input type="number" class="form-control" name="month" value="{{ request('month') }}"
                            placeholder="Mois (optionnel)">
                    </div>
                    <div class="col-lg-3 col-sm-12 col-sm-12 mb-3">
                        <input type="number" class="form-control" value="{{ request('year') }}" name="year"
                            placeholder="Year">
                    </div>
                    <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                        <button type="submit" class="btn btn-primary">Recherche</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ __('Nom') }}</th>
                            <th scope="col">{{ __('Tel') }}</th>
                            <th scope="col">{{ __('Salaire') }} (40%)</th>
                            <th scope="col">{{ __('Entré') }}</th>
                            <th scope="col">{{ __('Bonus') }}</th>
                            <th scope="col">{{ __('Avance') }}</th>
                            <th scope="col">{{ __('Total Salaire') }}</th>
                            <th scope="col">{{ __('Status') }}</th>
                            <th scope="col">{{ __('Mois') }}</th>
                            <th scope="col">{{ __('Année') }}</th>
                            <th scope="col">{{ __('Modifier') }}</th>
                            <th scope="col">{{ __('Imprimer') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <th scope="row">{{ $user->_id }}</th>
                            <td>{{ $user->_name }}</td>
                            <td>{{ $user->_phone }}</td>

                            <td>${{ $user->_salary }} (40%)</td>
                            <td>${{ $user->_hairdress }}</td>
                            <td>${{ $user->_bonus }}</td>
                            <td>${{ $user->_advance }}</td>
                            <td>${{ $user->_salary - $user->_advance }}</td>
                            <td>
                                @if ($user->_salaryStatus > 0)
                                <span class="badge badge-success">Apprové</span>
                                @else
                                <span class="badge badge-secondary">No Apprové</span>
                                @endif
                            </td>
                            <td>{{ $user->month }}</td>
                            <td>{{ $user->year }}</td>
                            @include('template.admin.action-drop', [
                                'route' => 'admin.salary.approved-now-date',
                                'id' => $user->_id
                            ])
                            <td>
                                <button type="button" class="btn btn-light btn-sm btn-icon-split report-modal"
                                    data-url="{{ route('admin.report.salary', [
                                        'uid' => $user->_id,
                                        'year' => $user->year,
                                        'month' => $user->month,
                                    ]) }}">Imprimer</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{ $users->links() }}
</div>
@endsection

resources/views/admin/_salary/_salaries/moderator.blade.php
@extends('admin._salary.salaries')

@section('salaries')
<div class="justify-content-center">
    <div class="card">
        <div class="card-header">
            <div class="mb-3">
            <button class="btn btn-primary btn-sm btn-icon-split" data-toggle="modal" data-target="#newSalary">
                <span class="text">{{ __('Ajouter Salaire') }}</span>
            </button>
            <small>( <strong>Année: {{ now()->format('Y') }}, Mois: {{ now()->format('m') }}</strong> )</small>
            </div>
            <div class="d-flex justify-content-between">
                <form method="GET" class="d-inline-block" action="" autocomplete="off">
                    <input type="hidden" name="uid" value="{{ request('uid') }}">
                    <div class="form-row">
                        <div class="col-lg-3 col-sm-12 col-sm-12 mb-3">
                            <div>
                                <button type="button" class="btn  btn-block btn-outline-info dropdown-toggle"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Recherche Travailleur
                                </button>
                                <div class="dropdown-menu shadow">
                                    <div class="mx-1">
                                        <div class="input-group">
                                            <input type="text" data-url="{{ route('search.worker') }}"
                                                data-target="Admin-Salary.hlsS"
                                                class="form-control bg-light border-0 small" placeholder="Recherche...">
                                        </div>
                                    </div>
                                    <div class="dropdown-divider mx-2" style="padding: 0 150px"></div>
                                    <div data-target="Admin-Salary.hlsSList"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                            <input type="text" class="form-control" id="worker_nameS" value="{{ $us ? $us->name : '' }}" readonly
                                placeholder="Travailleur (optionnel)">
                            <div class="valid-feedback"></div>
                        </div>
                        <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                            <input type="number" class="form-control" name="month" value="{{ request('month') }}"
                                placeholder="Mois (optionnel)">
                        </div>
                        <div class="col-lg-3 col-sm-12 col-sm-12 mb-3">
                            <input type="number" class="form-control" value="{{ request('year') }}" name="year"
                                placeholder="Year">
                        </div>
                        <div class="col-lg-2 col-sm-12 col-sm-12 mb-3">
                            <button type="submit" class="btn btn-primary">Recherche</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ __('Nom') }}</th>
                            <th scope="col">{{ __('Tel') }}</th>
                            <th scope="col">{{ __('Salaire') }}</th>
                            <th scope="col">{{ __('Avance') }}</th>
                            <th scope="col">{{ __('Total Salaire') }}</th>
                            <th scope="col">{{ __('Status') }}</th>
                            <th scope="col">{{ __('Mois') }}</th>
                            <th scope="col">{{ __('Année') }}</th>
                            <th scope="col">{{ __('Modifier') }}</th>
                            <th scope="col">{{ __('Imprimer') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($salaries as $salary)
                        <tr>
                            <th scope="row">{{ $salary->id }}</th>
                            <td>{{ $salary->user->name }}</td>
                            <td>{{ $salary->user->phone }}</td>

                            <td>${{ $salary->amount }}</td>
                            <td>${{ $salary->_advance }}</td>
                            <td>${{ $salary->amount - $salary->_advance }}</td>
                            <td>
                                @if ($salary->approved)
                                <span class="badge badge-success">Apprové</span>
                                @endif
                                @if ($salary->rejected)
                                <span class="badge badge-danger">Rejeté</span>
                                @endif
                            </td>
                            <td>{{ $salary->month }}</td>
                            <td>{{ $salary->year }}</td>
                            @include('template.admin.action-drop', [
                                'route' => 'admin.salary.salaries.moderators-approved',
                                'id' => $salary->id
                            ])
                            <td>
                                <button type="button" class="btn btn-light btn-sm btn-icon-split report-modal"
                                    data-url="{{ route('admin.report.salary-moderator', [
                                        'id' => $salary->id,
                                        'year' => $salary->year,
                                        'month' => $salary->month,
                                    ]) }}">Imprimer</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{ $salaries->links() }}
</div>

<div class="modal fade" id="newSalary" data-controller="Admin-SalaryModerator" tabindex="-1" role="dialog" aria-labelledby="newSalaryTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newSalaryTitle">{{ __('Avance') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="needs-validation" autocomplete="off" aria-autocomplete="none" method="POST"
                action="{{ route('admin.salary.salaries.moderators-newSalary') }}"
                data-action="Admin-SalaryModerator#newSalary">
                <div class="modal-body">
                    <div class="form-row">
                        <input type="hidden" name="uid">
                        <div class="col-md-6 col-12 mb-3">
                            <div>
                                <button type="button" class="btn  btn-block btn-outline-info dropdown-toggle"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Recherche Travailleur
                                </button>
                                <div class="dropdown-menu shadow">
                                    <div class="mx-1">
                                        <div class="input-group">
                                            <input type="text" data-url="{{ route('search.worker') }}"
                                                data-target="Admin-SalaryModerator.hls"
                                                class="form-control bg-light border-0 small" placeholder="Recherche...">
                                        </div>
                                    </div>
                                    <div class="dropdown-divider mx-2" style="padding: 0 150px"></div>
                                    <div data-target="Admin-SalaryModerator.hlsList"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-12 mb-3">
                            <input type="text" class="form-control" id="worker_name" readonly
                                placeholder="Travailleur (optionnel)">
                            <div class="valid-feedback"></div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="amount">{{ __('Montant') }}</label>
                            <input type="text" name="montant" value="0" class="form-control" id="amount" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Fermer') }}</button>
                    <button type="submit" class="btn btn-primary">{{ __('Enregistrer') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>   

@endsection